// api/reports/generate-pdf.js
// PDF generation endpoint that converts JSON report data to professional PDF
// Uses simple HTML-to-PDF conversion for Vercel compatibility

// Note: Puppeteer is not available in Vercel serverless environment
// Using a simpler approach for now

module.exports = async function handler(req, res) {
  const startTime = Date.now();
  const pdfId = `pdf-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
  
  // Set CORS headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  
  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  try {
    console.log(`[PDFGenerator] Starting PDF generation...`);
    
    // Validate request
    const { reportData, options = {} } = req.body;
    if (!reportData) {
      return res.status(400).json({
        success: false,
        error: 'Missing required field: reportData'
      });
    }

    console.log(`[PDFGenerator] Generating PDF for ${reportData.ticker}`);

    // For now, return a simple PDF placeholder since Puppeteer isn't available in Vercel
    // In production, this would use a PDF generation service or different approach
    const pdfContent = generateSimplePDFContent(reportData, options);

    // Create a simple PDF buffer (this is a placeholder - in real implementation would use proper PDF library)
    const pdfBuffer = Buffer.from(pdfContent, 'utf8');
    
    const generationTime = Date.now() - startTime;
    console.log(`[PDFGenerator] PDF generated in ${generationTime}ms`);

    // Return PDF as response (placeholder format for now)
    res.setHeader('Content-Type', 'text/plain');
    res.setHeader('Content-Disposition', `attachment; filename="${reportData.ticker}_Report_${new Date().toISOString().split('T')[0]}.txt"`);
    res.setHeader('Content-Length', pdfBuffer.length);

    return res.status(200).send(pdfBuffer);

  } catch (error) {
    const generationTime = Date.now() - startTime;
    console.error('[PDFGenerator] PDF generation failed:', error);
    
    return res.status(500).json({
      success: false,
      error: 'PDF generation failed',
      message: error.message,
      pdfId,
      generationTime
    });
  }
};

function generateSimplePDFContent(reportData, options) {
  const { ticker, slides, charts, aiAnalysis, rawData, metadata } = reportData;
  const quote = rawData?.quote || {};
  const profile = rawData?.profile || {};

  return `
${ticker} FINANCIAL ANALYSIS REPORT
Generated by TriSight AI Financial Intelligence Platform
Date: ${new Date().toLocaleDateString()}

COMPANY OVERVIEW
================
Company: ${profile.name || ticker}
Sector: ${profile.sector || 'N/A'}
Current Price: $${quote.close || 'N/A'}
Daily Change: ${quote.change || 'N/A'} (${quote.percent_change || 'N/A'}%)

EXECUTIVE SUMMARY
=================
${aiAnalysis?.marketAssessment || 'AI market assessment not available.'}

FINANCIAL HEALTH
================
${aiAnalysis?.financialHealth || 'AI financial analysis not available.'}

TECHNICAL ANALYSIS
==================
${aiAnalysis?.technicalAnalysis || 'AI technical analysis not available.'}

RISK ASSESSMENT
===============
${aiAnalysis?.riskAssessment || 'AI risk assessment not available.'}

INVESTMENT RECOMMENDATION
=========================
${aiAnalysis?.investmentRecommendation || 'AI investment recommendation not available.'}

DATA TRANSPARENCY
=================
Data Quality: ${metadata?.dataQuality || 0}%
Real Data Sources: ${metadata?.realDataSources || 0}
Report ID: ${metadata?.reportId || 'N/A'}

This report contains only real market data from TwelveData API.
No simulated data has been used.
AI analysis powered by Claude (Anthropic).

Generated by TriSight AI Financial Intelligence Platform
Report Quality: ${metadata?.dataQuality || 0}%
`;
}

// Simplified PDF generation - removed HTML styling functions
// In production, this would use a proper PDF library like PDFKit or jsPDF



// All HTML generation functions removed for simplified text-based PDF generation
